version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  bus-0:
    image: eclipse-mosquitto:latest
    container_name: bus-0
    ports:
      - "18830:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always

  bus-1:
    image: eclipse-mosquitto:latest
    container_name: bus-1
    ports:
      - "18831:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: always

volumes:
  mosquitto_data:
  mosquitto_log:
