[package]
name = "tt2-core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
fern = { version = "0.7.1", features = ["colored"] }
log = "0.4.27"
tokio = { version = "1.44.1", features = ["full"] }
